# Setup
title:        "Lizard Wrestling"
tagline:      Representing Edgewood and Lakeside Schools
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Cliff Frasure
  url:        "http://lizardwrestling.com"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
