# Setup
title:        "Lizard Wrestling"
tagline:      Buckeye and Ashtabula Schools
baseurl:      "/site"
paginate:     1

# About/contact
author:
  name:       Cliff Frasure
  url:        "http://lizardwrestling.com"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
