# Setup
title:        Lizard Wrestling
tagline:      test
baseurl:      "site"
paginate:     1

# About/contact
author:
  name:       Cliff Frasure
  url:        http://lizardwrestling.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
