# Setup
title:        "Ashtabula Wrestling"
tagline:      "Advancing the sport of wrestling at all levels"
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Cliff Frasure
  url:        "http://ashtabulawrestling.com"

# Gems
gems:
  - jekyll-paginate
  - jekyll-relative-links

#Others
markdown: kramdown
